### ISSUE TITLE
Text color

### ISSUE THREAD

**Issue by InkDevil666** [funkydude/BasicMinimap#39]
I have set the text color of Zone, Clock and Coordinates to be ClassColor, but they do not update to the right color when on another character. The border does change color as intended.

**Comment by wezhema** [comment]
Yea, on every log out the color of the clock is being reset.

**Comment by Lanacan** [comment]
I noticed that the clock color turns Grey color anytime there is a screen refresh such as zoning into or out of a dungeon or instance. 

To get it back I have to reselect the color in the options.

**Comment by slmcrs** [comment]
Yeah I noticed that color is not loaded until the color picker is opened for the clock. Others seem to work fine. When relogging the clock color is set back

**Comment by funkydude** [comment]
There is conflicting reports here. The original author @InkDevil666 is reporting that the text isn't class colored when they select the option. This isn't a feature of this addon, the option only affects the border. I can look into making this a feature if the original poster still wants it.

However, @wezhema @Lanacan & @slmcrs are reporting a completely different issue, your chosen clock color not being preserved.

This isn't a BasicMinimap issue, you actually have another addon installed that's changing the clock color.
I can try and work around this, but I need to know what addon is the cause. You will need to disable all your other addons until the issue is gone, then gradually enable a few addons at a time until the issue returns. This way you can locale the problematic addon and let me know.
I'd appreciate all 3 of you taking these steps, thanks.

**Comment by slmcrs** [comment]
> 
> 
> There is conflicting reports here. The original author @InkDevil666 is reporting that the text isn't class colored when they select the option. This isn't a feature of this addon, the option only affects the border. I can look into making this a feature if the original poster still wants it.
> 
> However, @wezhema @Lanacan & @slmcrs are reporting a completely different issue, your chosen clock color not being preserved.
> 
> This isn't a BasicMinimap issue, you actually have another addon installed that's changing the clock color.
> I can try and work around this, but I need to know what addon is the cause. You will need to disable all your other addons until the issue is gone, then gradually enable a few addons at a time until the issue returns. This way you can discover the problematic addon and let me know.
> I'd appreciate all 3 of you taking these steps, thanks.

Yea you are right, my apologies. I actually figured out that my color issue was being caused from Lorti UI Remake which applies a darkening effect over some of the blizzard ui elements. Using the addon with Basic Minimap caused the clock text to become all black unless the picker was opened, every time UI is reloaded.

**Comment by wezhema** [comment]
> There is conflicting reports here. The original author @InkDevil666 is reporting that the text isn't class colored when they select the option. This isn't a feature of this addon, the option only affects the border. I can look into making this a feature if the original poster still wants it.
> 
> However, @wezhema @Lanacan & @slmcrs are reporting a completely different issue, your chosen clock color not being preserved.
> 
> This isn't a BasicMinimap issue, you actually have another addon installed that's changing the clock color.
> I can try and work around this, but I need to know what addon is the cause. You will need to disable all your other addons until the issue is gone, then gradually enable a few addons at a time until the issue returns. This way you can discover the problematic addon and let me know.
> I'd appreciate all 3 of you taking these steps, thanks.

My apologies, you are correct, as @slmcrs says, I have Lorti UI Remake as well, that's the addon causing the issue

**Comment by funkydude** [comment]
@InkDevil666 The latest release now provides separate checkboxes to class color the clock/coords/zonetext.

**Comment by funkydude** [comment]
@wezhema @Lanacan @slmcrs The latest release implements its own clock code so conflicts with other addons should no longer occur.
