### ISSUE TITLE
Some errors maybe

### ISSUE THREAD

**Issue by marcelomax** [funkydude/BasicMinimap#44]
I'm having a lot of alert about incompatibility with "some blizzard" functions asking for disable addons. Most of time when i'm flying. When i accept the game disables just BasicMinimap. What i tried:
- keep it disabled for some time and watch behavior.
- Disabled Carbonite (because a lot of libs and easy to cause issues) and watch again.
- Use another square and nice minimap too and see what happen.

Every  test in case of BMinimap was disabled, i get no alert asking for disable addons.
Do we have some known incompatibility with another add on?

**Comment by funkydude** [comment]
Only you're able to find incompatibilities. I.e. disabling all your other addons and leave BasicMinimap on, and see if the issue occurs.

In regards to known issues, all minimap addons are highly vulnerable to incompatibility issues because we can't create our own Minimap from scratch, instead we have to decorate the one Blizzard creates, so all addons will need to "fight" over the edits being made.
