### ISSUE TITLE
Class Color border 

### ISSUE THREAD

**Issue by Icehole70** [funkydude/BasicMinimap#5]
Before the one of the last update, was able to have border match the class that I was playing. Now will only do the same color for the border for all character.

**Comment by funkydude** [comment]
Yeah, I'm thinking of adding profile options to work around this.

**Comment by funkydude** [comment]
Profile support added to the options, closing.

**Comment by malikoth** [comment]
With all of the alts that I play, I try to keep my addons configured as generically as possible so that default profiles work for the vast majority of cases.  I appreciate that it is now technically possible to have class colored border for each class, but that means I have to open the settings and switch profiles and hit the class color button for every alt.  On the one hand, that's not such a great burden individually, but it's one more thing I have to do to get my UI back when I log a toon I haven't played in awhile, and this is just one of many addons, all of which are always subtly in flux.

This is all part of my argument for why the I believe profile support is not the ideal solution for this problem.  I'd like the issue reopened if possible, and a different solution found.

My initial proposition would be to make it so that clicking the `Class Colored` button sets the value of `map.db.profile.colorBorder` to `nil`.  Then in the getter function for `colorBorder`, if `map.db.profile.colorBorder` is `nil`, return the class color of the player.

That way, it would be trivial to keep a default profile that works for all toons, and still matches the UI to my class.  If it would help, happy to submit a PR.

Thanks, you're the best!
