### ISSUE TITLE
[not a bug] Appreciation

### ISSUE THREAD

**Issue by tflo** [funkydude/BasicMinimap#50]
Obviously this is not an issue, but the lack of a forum on the add-on’s curseforge homepage forces me to post this here:

This add-on is insanely great, and does everything I expect – without all the Chinchilla/SexyMap bloat. Keep up the great work!

– Tom

**Comment by funkydude** [comment]
I appreciate the kind words.

If anyone wishes to, they can support my continued addon work my clicking the sponsor button at the top of this page.

**Comment by tflo** [comment]
> by clicking the sponsor button at the top of this page

I clicked and there are only subscriptions, unless I missed something. I hate subscriptions. Any way to make a normal donation?

**Comment by funkydude** [comment]
Unfortunately not. But it's the end of the month, you can subscribe and then cancel when it's taken off in a few days.

**Comment by tflo** [comment]
~Maybe~ Probably  I’ll do that. But don’t you think you scare many people off with this subscription-only model?

I’m well aware that it has become trendy for software developers to change to a subscription model. But, honestly, you can do this for the major and indispensable stuff (like Adobe applications, and MS Office nonsense, etc.), but if you accept much further, it will be out of hands quickly.

Of course, in this case, it’s doable, since the add-on doesn’t stop working when the sub times out. That is: It’s not really a subscription. But why on earth then offer only a subscription-only model? If you’d offer both, you wouldn’t scare people away, like me. (Even if at the end it’s the same.) You clearly need a marketing girl.

Think of it. It hurts me.

**Comment by funkydude** [comment]
I appreciate your comment and I'm sorry you feel that way, but unfortunately I don't have any plans for putting up a one time donation unless GitHub itself adds support for that. Maybe they have a suggestions section.

I am lucky that GitHub offers this service without taking any cut, and is free of various controversies that companies like Patreon have endured, which cost me many subscribers, whilst still taking a (growing) cut every month.

In regards to people donating 3 times a year: This just doesn't happen. Before subscription services I did have a 1 time donation option. I have thousands of users across all my addons and was lucky to get 1 small donation a year. People just prefer a $1 subscription because they can support authors long term without it breaking the monthly bank.

But like I said if GitHub add support I'd be happy to enable it. Until then subscribing and cancelling is a "hacky" workaround. If you don't want to do that, I totally respect that and I'm sorry you feel that way. But thanks for taking the time anyway.
