### ISSUE TITLE
Buff/debuff + boss frames anchoring improvement

### ISSUE THREAD

**Issue by addonaddict** [funkydude/BasicMinimap#55]
## Describe the problem
When using basicminimap, buff/debuff and boss frame windows need to be adjusted with a different addon (if you use a bigger minimap, it will be on top of these frames.

because of this issue - i either have to use additional addons like moveanything that spam errors (boss frames cant be moved properly without causing UI errors nonstop)
I would suggest if possible to allow anchoring the buff and boss frames to BasicMinimap map so that no matter what happens to your UI (such as changing UI scale % or by changing monitors which I do a lot) everything will always be in correct location. Having to readjust everything and deal with multiple addons for something like this is unfortunately why I had to delete the addon..

### What steps will reproduce the problem?

1.  make a minimap big at top right corner, all frames will be hidden behind..

### What version of the addon are you using? (Stating 'latest' is not useful)
v9.0.5

### Do you have an error log of what happened?
no errors

Thank you so much

**Comment by funkydude** [comment]
Thanks for taking the time to make this suggestion. It's a valid problem that's for sure, but unfortunately it's not a problem I want to personally deal with in this addon, sorry. The code involved can be messy, and it opens up a whole new area of things that I need to maintain and support, especially in regards to "playing nice" with other addons.

If you don't want to use MoveAnything because you feel it is not maintained, I can suggest one of my addons for moving the buff frame: https://www.curseforge.com/wow/addons/basicbuffs

I have no suggestions for boss frames or quest tracker other than dedicated unit frame addons & quest tracker addons.
