### ISSUE TITLE
How to return tracking icon?

### ISSUE THREAD

**Issue by SegoItCh** [funkydude/BasicMinimap#74]
I can't find my tracking icon, so I don't know what I'm tracking right now

**Comment by SegoItCh** [comment]
Have error for you too :D

1x BasicMinimap_Options\Options_Wrath.lua:357: Attempt to find 'this' in non-table object (used '.' instead of ':' ?)
[string "=[C]"]: in function `SetParent'
[string "@BasicMinimap_Options\Options_Wrath.lua"]:357: in function <BasicMinimap_Options\Options_Wrath.lua:353>
[string "=[C]"]: ?
[string "@BlizzMove\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-83.lua"]:45: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:43>
[string "@BlizzMove\Libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-83.lua"]:827: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:649>
[string "=[C]"]: ?
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Attune\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Attune\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-CheckBox.lua"]:68: in function <...ne\Libs\AceGUI-3.0\widgets\AceGUIWidget-CheckBox.lua:57>

**Comment by funkydude** [comment]
Thanks for reporting that error, it's now fixed in the latest release.

In regards to the tracking icon, that's intentional and is unlikely to change. Replacing buttons with minimap clicks is a core feature of this addon.

For example, the default mouse click for tracking is middle mouse, and you can change this in the options.
